### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by bauer-alex** [FabienM/fitbit-face-digitless#20]
I'd highly appreciate a German version of the watch face.
If you don't mind I'd implement it and open a PR.

**Comment by FabienM** [comment]
Hi @bauer-alex, sorry for the long time without answer, i'm also using github for professional work and the notification has been drowned between hundred of others.

Of course, i would be glad to accept your contribution with a german translation.
Unfortunately, the app does not take advantage of the i18n API released in the 3.1 SDK version. You will find the translation label and rules in the `time.ts` file.

`DateTimeInWords12h.formatNumer` is the place where you will want to put any german-specific rules to format number.

Let me know if you need help.

I leave this issue open since i may give a look myself to german translation rules if i don't hear from you until then ;-)

**Comment by bauer-alex** [comment]
Nice to see that you implemented the German localization yourself!

Is everything clear about the German translation or do you still need some feedback?

**Comment by FabienM** [comment]
Hi Alex,

I made a shot that you can already try if you want.
A release is in the validation process on fitbit’s side, i will let you
know when it will be available right from the application gallery.

In the meantime, if you have development knowledge, you can try to install
the 1.3.0-pre.0 draft release build from github
<https://github.com/FabienM/fitbit-face-digitless/releases/tag/untagged-42e4b514b5b4a73710a0>

You'll see that i had to decrease font size for german size most number
were too long for the screen. At the moment i did not manage to properly
adapt the layout to the new font size so there is a blank space between the
time and the separator bar.

**Comment by bauer-alex** [comment]
Sounds fine!
So I'll wait for the watchface to be officially released to try it out.

**Comment by FabienM** [comment]
Still in the validation process :-)

You can checkout versa and ionic layouts here:
![image](https://github.com/FabienM/fitbit-face-digitless/blob/master/docs/screenshots/de-versa.png)
![image](https://github.com/FabienM/fitbit-face-digitless/blob/master/docs/screenshots/de-ionic.png)

**Comment by FabienM** [comment]
Hi @bauer-alex 

The update has finally been approved by fitbit and should be available on the application gallery for you to install.

https://gallery.fitbit.com/details/c95aa4a1-712f-475e-93e0-2964b74445bb

Let me know what you think!

**Comment by bauer-alex** [comment]
Nice job, I really like it!

Nothing big to complain from my side. Only thing is that I would rather write the weekdays as Mo / Di / etc instead of mon / die / ...
And I would introduce one blank between the weekday and the date.

What do you think?
